### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by sogoagain** [CodeSoom/project-react-1-sogoagain#1]
1. 이 앱을 언제 사용하나요?

아이디어 발굴을 할 때 사용합니다. 새로운 아이템, 서비스 등을 기획하기 위해서는 아이디어가 필요합니다. 그러나, 아이디어는 잘 떠오르지 않습니다. 이럴 때 앱이 영감을 불러일으켜 줍니다.

2. 제약 조건은 무엇인가요?

앱 메인 화면에 `${누구}를 위한 ${무엇}` 형태의 아이디어가 매번 임의로 출력되어야 합니다.
사용자는 `${누구}`와 `${무엇}`에 해당하는 데이터 셋에 자유롭게 데이터를 추가할 수 있어야 합니다.
사용자는 마음에 드는 아이디어에 '좋아요'를 누를 수 있어야 합니다.
제일 최근에 '좋아요'가 눌린 순서로 아이디어 목록을 확인할 수 있어야 합니다.

3. 구체적인 사례는 무엇인가요?

프로젝트 아이템을 구상 중인데 아이디어가 잘 떠오르지 않습니다. 앱을 켜고 임의로 생성된 아이디어를 확인 합니다. 영감을 주는 아이디어가 나타날 때 까지 새로고침 합니다. 영감을 주는 아이디어를 발견 했다면 '좋아요'를 눌러 표시합니다. 이 아이디어를 바탕으로 프로젝트 아이템을 상세화합니다.

4. 이번주에 구현 할 기능을 우선 순위대로 작성해주세요.

- [x] [개발 환경 구성](https://github.com/CodeSoom/project-react-1-sogoagain/issues/8)
- [x] [아이디어 출력 기능 구현](https://github.com/CodeSoom/project-react-1-sogoagain/issues/3)
- [x] [아이디어 새로고침 기능 구현](https://github.com/CodeSoom/project-react-1-sogoagain/issues/2)

**Comment by sogoagain** [comment]
# 9주차 회고

## Facts (한 것)

- 프로젝트 아이디어를 선정 했다.
- 개발 환경을 구성하고 첫 기능 두가지를 개발 하였다.

## Feelings (느낀 것)

- 아이디어 선정에 많은 고민이 있었다.
- 4주 안에 Front-end와 Back-end 구현을 완료할 수 있고, 실제 사람들이 사용할 수 있는 Application을 프로젝트로 제작하고 싶었다.
- 고민을 거듭하다 보니 시간을 많이 투여되는데 시작이 늦어지는 것 같아 초조하였다.


## Findings (배운 것)

- 초기 브레인 스토밍 작업이 매우 중요하다는 것을 깨달았다.
- 또한, 초기에 정한 아이디어를 빠르게 실험해보는 자세가 필요하다.

## Future (할 것)

- 아이디어 선정의 고민이 끝난 것이 아니라 화면에 보이는 디자인으로 이어졌다. 계속해서 고민 중인데 시간 내어 디자인 가이드를 잡아야겠다.
- CI 도입 및 기능 구현을 계속해 나갈 것이고, Backend 구현도 시작할 예정이다.
