### ISSUE TITLE
2주차 진행

### ISSUE THREAD

**Issue by sogoagain** [CodeSoom/project-react-1-sogoagain#14]
1. 이 앱을 언제 사용하나요?

아이디어 발굴을 할 때 사용합니다. 새로운 아이템, 서비스 등을 기획하기 위해서는 아이디어가 필요합니다. 그러나, 아이디어는 잘 떠오르지 않습니다. 이럴 때 앱이 영감을 불러일으켜 줍니다.

2. 제약 조건은 무엇인가요?

앱 메인 화면에 `${누구}를 위한 ${무엇}` 형태의 아이디어가 매번 임의로 출력되어야 합니다.
사용자는 `${누구}`와 `${무엇}`에 해당하는 데이터 셋에 자유롭게 데이터를 추가할 수 있어야 합니다.
사용자는 마음에 드는 아이디어에 '좋아요'를 누를 수 있어야 합니다.
제일 최근에 '좋아요'가 눌린 순서로 아이디어 목록을 확인할 수 있어야 합니다.

3. 구체적인 사례는 무엇인가요?

프로젝트 아이템을 구상 중인데 아이디어가 잘 떠오르지 않습니다. 앱을 켜고 임의로 생성된 아이디어를 확인 합니다. 영감을 주는 아이디어가 나타날 때 까지 새로고침 합니다. 영감을 주는 아이디어를 발견 했다면 '좋아요'를 눌러 표시합니다. 이 아이디어를 바탕으로 프로젝트 아이템을 상세화합니다.

4. 이번주에 구현 할 기능을 우선 순위대로 작성해주세요.

- [x] [CI 환경 구성 #12](https://github.com/CodeSoom/project-react-1-sogoagain/issues/12)
- [x] [API 서버 개발 #13](https://github.com/CodeSoom/project-react-1-sogoagain/issues/13)
- [x] [사용자는 다양한 아이디어를 구성하기 위해 특정 대상(물건, 상품 등)을 제안할 수 있다. #6](https://github.com/CodeSoom/project-react-1-sogoagain/issues/6)
- [x] [사용자는 다양한 아이디어를 구성하기 위해 어떤 사람을 위한 것인지 제안할 수 있다. #7](https://github.com/CodeSoom/project-react-1-sogoagain/issues/7)

**Comment by hannut91** [comment]
이미 사용할 수 있는 기능이 다 되네요!

**Comment by sogoagain** [comment]
> 이미 사용할 수 있는 기능이 다 되네요!

비교적 간단한 서비스라 기능들을 얼른 개발해서 디자인 작업에 들어가야할 것 같아요. :)

**Comment by sogoagain** [comment]
# 10주차 회고

## Facts (한 것)

- CI 환경을 구성했다.
- AWS 서비스(API Gateway, Lambda, DynamoDB)를 이용해 API 서버를 개발했다.
- 사용자가 아이디어를 제안할 수 있는 화면을 개발했다.

## Feelings (느낀 것)

- API 서버 개발에 생각보다 많은 공수가 들었다. 간단한 API라 금방 만들 수 있으리라 생각했는데, 역시나 착오였다. DynamoDB에서 무작위로 Item을 쿼리 하는 것이 기본적으로 제공되지 않아 해결하고자 이런저런 방법들을 많이 사용해보았다. 그 과정에서 테이블 스키마를 계속해서 엎어야 했는데 이 덕분에 NoSQL 기반의 DynamoDB를 더 깊이 이해할 수 있었고 테이블 스키마를 설계하는 데 있어 RDB와 다른 점을 경험으로 느낄 수 있었다.
- CI 환경도 만만치 않았다. 특히 Github의 프로젝트 페이지에는 저장소 이름으로 기본 path가 붙어 있는데, 이를 해결하는 과정에서 자잘한 오류들을 계속해서 만나게 되었다. 덕분에 웹팩과 React Router에 대해 이해도가 높아졌다.
- 얼른 디자인을 입혀야 하는데, 디자인 감각이 부족해 걱정이다.

## Findings (배운 것)

- NoSQL 기반의 DynamoDB는 '파티션 키'와 '정렬 키'를 어떻게 구상해야 하는지가 핵심이다. 이 두 가지를 적절하게 조합하면 RDB에서 여러 테이블에 나타내야 할 데이터를 한 테이블에서 효율적으로 표현할 수 있다.
- Github Action을 통해 정말 편하게 CI/CD 환경을 구축할 수 있다. 앞으로 자주 써먹자.
- 프로젝트를 시작했다면 최대한 빨리 개발부터 배포까지 한 사이클을 돌아야 밝은 미래로 나아갈 수 있다.

## Future (할 것)

- 스토리를 작성할 때 일정 추정도 같이 해야 할 것 같다. 그뿐만 아니라 작업이 끝나면 추정했던 일정과 실제 걸렸던 일정을 비교해보자.
- 서비스의 디자인을 구상해보자.
